--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Actions (extracted from services).
  name: actions
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Commandline interface controller.
  name: cli
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Syckle mater configuration.
  name: config
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Input/Ouput controller.
  name: io
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Run context.
  name: script
  rw: R
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::H 
  level: 1
  text: Application
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Probably rename this class --&quot;Application&quot; is too generic. TODO: Continue to imporve CLI layer."
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::H 
  level: 1
  text: Application
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Probably rename this class --&quot;Application&quot; is too generic. TODO: Continue to imporve CLI layer."
constants: []

full_name: Syckle::Application
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: active_services
- !ruby/object:RDoc::RI::MethodSummary 
  name: config_template
- !ruby/object:RDoc::RI::MethodSummary 
  name: defaults
- !ruby/object:RDoc::RI::MethodSummary 
  name: end_phases
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_plugins
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_project_plugins
- !ruby/object:RDoc::RI::MethodSummary 
  name: multitask?
- !ruby/object:RDoc::RI::MethodSummary 
  name: overview
- !ruby/object:RDoc::RI::MethodSummary 
  name: project
- !ruby/object:RDoc::RI::MethodSummary 
  name: run
- !ruby/object:RDoc::RI::MethodSummary 
  name: run_a_service
- !ruby/object:RDoc::RI::MethodSummary 
  name: runscript
- !ruby/object:RDoc::RI::MethodSummary 
  name: service_calls
- !ruby/object:RDoc::RI::MethodSummary 
  name: service_configs
- !ruby/object:RDoc::RI::MethodSummary 
  name: skip
- !ruby/object:RDoc::RI::MethodSummary 
  name: start
name: Application
superclass: Object
