--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
<<<<<<< HEAD:ri/Syckle/Application/config_template-i.yaml
  body: Generates a master configuration template. This is only used for reference purposes.
=======
  body: Generates a master configuration template. This is only used for reference.
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/Application/config_template-i.yaml
full_name: Syckle::Application#config_template
is_singleton: false
name: config_template
params: ()
visibility: public
