--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: This substitutes environment vairables in for service options if they are given in the form of +ENV[NAME]+.
full_name: Syckle::Application#inject_environment
is_singleton: false
name: inject_environment
params: (options)
visibility: public
