.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DETROIT" "1" "October 2011" "" ""
.
.SH "NAME"
\fBdetroit\fR \- ruby life\-cycle build tool
.
.SH "DESCRIPTION"
Detroit is a software production management aid for Ruby developers\. Detroit utilizes a life\-cycle methodology to help developers prepare and release Ruby software in a clear, repeatable, linear fashion\.
.
.SH "USAGE"
To utilize Detroit add an \fBAssembly\fR or \fB*\.assembly\fR file to your project\'s root directory\. In this file add instantiation of service tools, configured to your projects build requirements\. Assembly files can be written in YAML or Ruby\.
.
.P
For example to generate RDoc\'s for a project, a service might be defined:
.
.IP "" 4
.
.nf

rdoc:
  service: rdoc
  files:
    \- lib
    \- \'[A\-Z]*\.*\'
  main: README\.md
.
.fi
.
.IP "" 0
.
.P
See the online User Guide \fIhttp://wiki\.rubyworks\.github\.com/detroit\fR for more details on creating assembly files\.
.
.P
Once an assembly file is in place, the \fBdetroit\fR command line tool can be used to invoke the service\. For example, to generate documentation:
.
.IP "" 4
.
.nf

$ detroit document
.
.fi
.
.IP "" 0
.
.P
This will run through all standard stops up to and include the document stop\. Since the RDoc service we setup above defines document job, it would be run in due course\.
.
.SH "OPTIONS"
These are the available options for the \fBdetroit\fR command line tool\.
.
.IP "\(bu" 4
\fB\-m\fR, \fB\-\-multitask\fR Run work elements in parallel\.
.
.IP "\(bu" 4
\fB\-S\fR, \fB\-\-skip=SERVICE\fR Skip a service\.
.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-system=NAME\fR Select assembly system\. Default is \'standard\'\.
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-assembly=FILE\fR Use specific assembly file(s)\.
.
.IP "\(bu" 4
\fB\-F\fR, \fB\-\-force\fR Force operations\.
.
.IP "\(bu" 4
\fB\-\-trace\fR Run in TRACE mode\.
.
.IP "\(bu" 4
\fB\-\-trial\fR Run in TRIAL mode (no disk writes)\.
.
.IP "\(bu" 4
\fB\-\-verbose\fR Provide extra output\.
.
.IP "\(bu" 4
\fB\-q\fR, \fB\-\-quiet\fR Run silently\.
.
.IP "\(bu" 4
\fB\-I=PATH\fR Add directory to $LOAD_PATH
.
.IP "\(bu" 4
\fB\-\-debug\fR Run with $DEBUG set to true\.
.
.IP "\(bu" 4
\fB\-\-warn\fR Run with $VERBOSE set to true\.
.
.IP "\(bu" 4
\fB\-\-help [TOOL]\fR Display this help message\.
.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-config=TOOL\fR Produce a configuration template\.
.
.IP "" 0
.
.SH "RESOURCES"
.
.IP "\(bu" 4
Homepage \fIhttp://rubyworks\.github\.com/detroit\fR
.
.IP "\(bu" 4
Development \fIhttp://github\.com/rubyworks/detroit\fR
.
.IP "\(bu" 4
Mailing List \fIhttp://googlegroups\.com/group/rubyworks\-mailinglist\fR
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright (c) Thomas Sawyer, 2011
.
.P
Detroit is distributable in accordance with the terms of the GPL v\.3 license\.
