--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Set list of services to omit from automatic execution.
full_name: Syckle::Config#auto_omit=
is_singleton: false
name: auto_omit=
params: (entry)
visibility: public
