--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Services to omit from automatic execution. Should be an array of service names (class basenames).
  name: auto_omit
  rw: RW
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Use automatic services feature?
  name: automatic
  rw: RW
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load load from a YAML project file saved as '.config/syckle.yml'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Better name for auto_omit."
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load load from a YAML project file saved as '.config/syckle.yml'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Better name for auto_omit."
constants: []

full_name: Syckle::Config
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: auto_omit=
- !ruby/object:RDoc::RI::MethodSummary 
  name: automatic?
name: Config
superclass: Object
