--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
<<<<<<< HEAD:ri/Syckle/Config/cdesc-Config.yaml
    body: Use automatic services feature? If set to <tt>true</tt>, all services with autorun modes will run if their autorun criteria is met. Or this can be set to a list of service names for which autorun mode will apply.
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Default is <tt>true</tt>. Use <tt>false</tt> to deactivate.
  name: automatic
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Service defaults. This is a mapping of service names to default settings. Very useful for autorun mode.
  name: defaults
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Current POM::Project object.
  name: project
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Service configurations. This is a hash of parameters.
  name: services
  rw: R
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Services to omit from automatic execution. If automatic is set to <tt>true</tt> (the default), the <tt>standard</tt> setting can be used to exclude specific services from auto-execution.
  name: standard
  rw: R
=======
    body: Services to omit from automatic execution. Should be an array of service names (class basenames).
  name: auto_omit
  rw: RW
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Use automatic services feature?
  name: automatic
  rw: RW
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/Config/cdesc-Config.yaml
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
<<<<<<< HEAD:ri/Syckle/Config/cdesc-Config.yaml
  body: Syckle configuration. Configuration comes from a main <tt>Syckfile</tt> and/or <tt>.syckle</tt> task files, and configuration options defined in a path store in the project's config directory (eg. <tt>.config/syckle/</tt>).
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to accept a list of serives to limit automatic mode."
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle configuration. Configuration comes from a main <tt>Syckfile</tt> and/or <tt>.syckle</tt> task files, and configuration options defined in a path store in the project's config directory (eg. <tt>.config/syckle/</tt>).
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to accept a list of serives to limit automatic mode."
=======
  body: Syckle master configuration. Configuration settings load load from a YAML project file saved as '.config/syckle.yml'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Better name for auto_omit."
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load load from a YAML project file saved as '.config/syckle.yml'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Better name for auto_omit."
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/Config/cdesc-Config.yaml
constants: []

full_name: Syckle::Config
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
<<<<<<< HEAD:ri/Syckle/Config/cdesc-Config.yaml
  name: automatic=
- !ruby/object:RDoc::RI::MethodSummary 
  name: automatic?
- !ruby/object:RDoc::RI::MethodSummary 
  name: defaults=
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_syckle_file
- !ruby/object:RDoc::RI::MethodSummary 
  name: method_missing
- !ruby/object:RDoc::RI::MethodSummary 
  name: standard=
- !ruby/object:RDoc::RI::MethodSummary 
  name: standard?
- !ruby/object:RDoc::RI::MethodSummary 
  name: syckle_files
=======
  name: auto_omit=
- !ruby/object:RDoc::RI::MethodSummary 
  name: automatic?
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/Config/cdesc-Config.yaml
name: Config
superclass: Object
