--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load from a YStore located at '.config/syckle/'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load from a YStore located at '.config/syckle/'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
constants: []

full_name: Syckle::Config
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: automatic
- !ruby/object:RDoc::RI::MethodSummary 
  name: automatic?
- !ruby/object:RDoc::RI::MethodSummary 
  name: defaults
- !ruby/object:RDoc::RI::MethodSummary 
  name: manual
name: Config
superclass: Object
