--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: automatic
  rw: RW
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: defaults
  rw: RW
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: manual
  rw: RW
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: services
  rw: RW
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load from a YStore located at '.config/syckle/'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Syckle master configuration. Configuration settings load from a YStore located at '.config/syckle/'.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "TODO: Allow <tt>automatic</tt> to be a list of serive names to active"
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "      automatic mode for.\n"
constants: []

full_name: Syckle::Config
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_service_configs
name: Config
superclass: Object
