--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Service defaults. This is a mapping of service names to default settings. Very useful for autorun mode.
full_name: Syckle::Config#defaults
is_singleton: false
name: defaults
params: ()
visibility: public
