--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Syckle::Config#load_syckle_file
is_singleton: false
name: load_syckle_file
params: (file)
visibility: public
