--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Load service configs for a select set of syckle scripts/tasks.
full_name: Syckle::Config#load_service_configs
is_singleton: false
name: load_service_configs
params: (project)
visibility: private
