--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Syckle::Config#method_missing
is_singleton: false
name: method_missing
params: (sym, *args)
visibility: public
