--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
<<<<<<< HEAD:ri/Syckle/Config/new-c.yaml
comment: []

full_name: Syckle::Config::new
is_singleton: true
name: new
params: (project)
=======
comment: 
full_name: Syckle::Config::new
is_singleton: true
name: new
params: ()
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/Config/new-c.yaml
visibility: public
