#!/usr/bin/env ruby

ignore 'pkg', 'web'

#desc "Release and announce new package."
#task 'release' do
#  exit -1 if !system('detroit promote')  # `detroit release`
#  system "pom news | git tag -a -F - #{version}"
#end

file 'var/*' do
  system 'index -u var'
end

file 'MANIFEST' do
  update_manifest
end

file 'lib/**/*' do
  exit -1 if !system('detroit test')
  update_manifest
end

def update_manifest
  @update_manifest ||= system "mast -u"
end

# Integrate git hooks ?
#git :tag do
#  `pom news | git tag -a -F - #{version}`
#end

