--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
<<<<<<< HEAD:ri/Syckle/CLI/application-i.yaml
comment: []

=======
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: def help
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "  usage.help.to_s(:bold=&gt;true)\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: end
>>>>>>> 5decbf1bc6cee8b7cedf216152e8021212909f00:ri/Syckle/CLI/application-i.yaml
full_name: Syckle::CLI#application
is_singleton: false
name: application
params: ()
visibility: public
