--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: def help
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "  usage.help.to_s(:bold=&gt;true)\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: end
full_name: Syckle::CLI#application
is_singleton: false
name: application
params: ()
visibility: public
