--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Syckle::Config::TMP#method_missing
is_singleton: false
name: method_missing
params: (s)
visibility: public
