--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Load configuration data from a file. Results are cached and and empty Hash is returned if the file is not found.
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Since they are YAML files, they can optionally end with '.yaml' or '.yml'.
full_name: Syckle::Script#configuration
is_singleton: false
name: configuration
params: (file)
visibility: public
