#!/usr/bin/env ruby

# TODO: How to include another seed? Syckle needs the 'pom' seed.
# We are replicating it here for now.

utilize 'pom'

setup do |*args|
  name = args.first || metadata['name'] || destination.basename.to_s

  abort "Name is required."         unless name
  abort "Name must be single word." unless name =~ /\w+/

  metadata.name    = name
  metadata.title   = metadata['title'] || name.capitalize
  metadata.contact = metadata['EMAIL']
end

scaffold do
  copy "Syckfile"

  unless (destination + "PROFILE").exist?
    copy "PROFILE"
  end

  unless (destination + "PACKAGE").exist?
    copy "PACKAGE"
  end
end

