--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Syckle::Emailer::environment_options
is_singleton: true
name: environment_options
params: ()
visibility: public
