--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Syckle::Emailer::new_with_environment
is_singleton: true
name: new_with_environment
params: (options={})
visibility: public
